apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-apps-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: example.local
    - http:
        paths:
          - path: /nginx
            pathType: Prefix
            backend:
              service:
                name: simple-nginx-service
                port:
                  number: 80
          - path: /httpd
            pathType: Prefix
            backend:
              service:
                name: simple-httpd-service
                port:
                  number: 80
