apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-httpd-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: 34.66.94.32.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-httpd-service
                port:
                  number: 80
